name: Release

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: latest
          cache: true

      - name: Build conda package
        run: pixi build

      - name: Upload to prefix.dev
        run: |
          pixi upload prefix \
            --channel thath \
            ./*.conda
